IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_CONFIG]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_CONFIG (
    CONFIG_KEY VARCHAR(255) NOT NULL,
    CONFIG_VALUE VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (TENANT_ID, CONFIG_KEY)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY (
    POLICY_ID VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL,
    IS_IN_PAP BIT NOT NULL DEFAULT 1,
    IS_IN_PDP BIT NOT NULL DEFAULT 0,
    POLICY TEXT NOT NULL,
    IS_ACTIVE BIT NOT NULL DEFAULT 0,
    POLICY_TYPE VARCHAR(255) NOT NULL,
    POLICY_EDITOR VARCHAR(255),
    POLICY_ORDER INTEGER NOT NULL,
    LAST_MODIFIED_TIME DATETIME NOT NULL,
    LAST_MODIFIED_USER VARCHAR(255),
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (POLICY_ID, VERSION, TENANT_ID),
    CONSTRAINT IDN_XACML_POLICY_KEY_CONSTRAINT UNIQUE (POLICY_ID, VERSION, TENANT_ID)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY_ATTRIBUTE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY_ATTRIBUTE (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    ATTRIBUTE_ID VARCHAR(255) NOT NULL,
    ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
    DATA_TYPE VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (POLICY_ID, VERSION, TENANT_ID) REFERENCES IDN_XACML_POLICY (POLICY_ID, VERSION, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY_EDITOR_DATA]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY_EDITOR_DATA (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    DATA VARCHAR(500),
    DATA_ORDER INTEGER NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (POLICY_ID, VERSION, TENANT_ID) REFERENCES IDN_XACML_POLICY (POLICY_ID, VERSION, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY_REFERENCE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY_REFERENCE (
    REFERENCE VARCHAR(255) NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (REFERENCE, POLICY_ID, VERSION, TENANT_ID),
    FOREIGN KEY (POLICY_ID, VERSION, TENANT_ID) REFERENCES IDN_XACML_POLICY (POLICY_ID, VERSION, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY_SET_REFERENCE]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY_SET_REFERENCE (
    SET_REFERENCE VARCHAR(255) NOT NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (SET_REFERENCE, POLICY_ID, VERSION, TENANT_ID),
    FOREIGN KEY (POLICY_ID, VERSION, TENANT_ID) REFERENCES IDN_XACML_POLICY (POLICY_ID, VERSION, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_SUBSCRIBER]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_SUBSCRIBER (
    SUBSCRIBER_ID VARCHAR(255) NOT NULL,
    ENTITLEMENT_MODULE_NAME VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (SUBSCRIBER_ID, TENANT_ID),
    CONSTRAINT IDN_XACML_SUBSCRIBER_KEY_CONSTRAINT UNIQUE (SUBSCRIBER_ID, TENANT_ID)
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_SUBSCRIBER_PROPERTY]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_SUBSCRIBER_PROPERTY (
    PROPERTY_ID VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    PROPERTY_VALUE VARCHAR(2000) NOT NULL,
    IS_REQUIRED BIT NOT NULL DEFAULT 0,
    DISPLAY_ORDER INTEGER NOT NULL,
    IS_SECRET BIT NOT NULL DEFAULT 0,
    PROPERTY_MODULE VARCHAR(255),
    SUBSCRIBER_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (PROPERTY_ID, SUBSCRIBER_ID, TENANT_ID),
    FOREIGN KEY (SUBSCRIBER_ID, TENANT_ID) REFERENCES IDN_XACML_SUBSCRIBER (SUBSCRIBER_ID, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_SUBSCRIBER_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_SUBSCRIBER_STATUS (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    IS_SUCCESS BIT NOT NULL DEFAULT 0,
    USERNAME VARCHAR(255) NOT NULL,
    TARGET VARCHAR(255) NOT NULL,
    TARGET_ACTION VARCHAR(255) NOT NULL,
    LOGGED_AT DATETIME NOT NULL,
    MESSAGE VARCHAR(255) NULL,
    SUBSCRIBER_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SUBSCRIBER_ID, TENANT_ID) REFERENCES IDN_XACML_SUBSCRIBER (SUBSCRIBER_ID, TENANT_ID) ON DELETE CASCADE
);

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_XACML_POLICY_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE IDN_XACML_POLICY_STATUS (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    IS_SUCCESS BIT NOT NULL DEFAULT 0,
    USERNAME VARCHAR(255) NOT NULL,
    TARGET VARCHAR(255) NOT NULL,
    TARGET_ACTION VARCHAR(255) NOT NULL,
    LOGGED_AT DATETIME NOT NULL,
    MESSAGE VARCHAR(255) NULL,
    POLICY_ID VARCHAR(255) NOT NULL,
    POLICY_VERSION INTEGER NOT NULL DEFAULT -1,
    TENANT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

-- XACML --
CREATE INDEX IDX_POLICY_ATTRIBUTE ON IDN_XACML_POLICY_ATTRIBUTE (POLICY_ID, VERSION, TENANT_ID);
CREATE INDEX IDX_POLICY_EDITOR_DATA_FK ON IDN_XACML_POLICY_EDITOR_DATA (POLICY_ID, VERSION, TENANT_ID);
CREATE INDEX IDX_POLICY_REF ON IDN_XACML_POLICY_REFERENCE (POLICY_ID, VERSION, TENANT_ID);
CREATE INDEX IDX_POLICY_SET_REF ON IDN_XACML_POLICY_SET_REFERENCE (POLICY_ID, VERSION, TENANT_ID);
CREATE INDEX IDX_SUBSCRIBER_PROPERTY ON IDN_XACML_SUBSCRIBER_PROPERTY (SUBSCRIBER_ID, TENANT_ID);
CREATE INDEX IDX_XACML_SUBSCRIBER_STATUS ON IDN_XACML_SUBSCRIBER_STATUS (SUBSCRIBER_ID, TENANT_ID);
CREATE INDEX IDX_XACML_POLICY_STATUS ON IDN_XACML_POLICY_STATUS (POLICY_ID, POLICY_VERSION, TENANT_ID);
